name: "🚀 Feature request"
description: Suggest a feature that will improve things
labels: ["enhancement"]
title: "[Feature Request] Your descriptive title here!"
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition, including the possible use cases and alternatives you have considered. If you have a working prototype or something similar, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please understand and agree to this
      options:
        - label: I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.
          required: true